### PR TITLE
Release v1.0.3

### PR DESCRIPTION
**Pull request by lovell**
Includes the following changes:

* Add range checks to guard against invalid input (#5)
* Exit early in case of unknown or bogus tag type (#9)
* Don't try to use a non-integer as an offset into the buffer (#14)
* Create dates from the UTC fields in one go (#15)
* Add fuzz testing setup (#6)
* Prevent tests and fixtures being published to npm (#13)

### CODE REVIEW

**Review by devongovett — APPROVED** [review]
lgtm!

We should probably set up GitHub actions to publish to npm automatically when a version tag is created or something. I can add you on npm or release it myself for now if you like though.

**Comment by lovell** [comment]
Happy for you to either manually publish for now or add me to npm (username is ~lovell), whichever is easier for you, thanks.

Definitely a :+1: for investigating automagic test+publish via GitHub Actions, great idea.

**Comment by devongovett** [comment]
@lovell I've added you as a maintainer on npm. Thanks again!

**Comment by lovell** [comment]
Thanks, v1.0.3 now available via npm.

**Pull request merged**
