### PR TITLE
Exif from PNGs with eXIf chunk

### PR DESCRIPTION
**Pull request by paxvista**

### CODE REVIEW

**Comment by lovell** [comment]
Hi Bob, thank you for the PR, this should fix https://github.com/devongovett/exif-reader/issues/19

Did you see a possible alternative approach from @rexxars in commit https://github.com/sanity-io/exif-reader/commit/6ee2ee2f243cd6365ff4235a63797615a983fae1 ? If nothing else it might be good to include the test case here also.

**Comment by paxvista** [comment]
The approach from @rexxars is definitely more elegant, but creates a new buffer, which was something I was trying to avoid. Are you suggesting I include his test in my pull request?

**Review by lovell — APPROVED** [review]
LGTM, I agree with the use of offsets rather than copy/concat. I'll leave this here for a few days for any further feedback from other maintainers/contributors before merging. Thank you!

**Comment by squaredx** [comment]
Hi all! Is there any status update on when this will be merged into main?

**Comment by lovell** [comment]
Sure, there's been no other feedback, let's merge.

**Comment by squaredx** [comment]
@lovell thank you so much! 🙌

**Comment by ToPeas** [comment]
how long will the publish new release? thanks. i really need this feature that parse png exif.

**Comment by lovell** [comment]
v1.1.0 now available via npm

**Pull request merged**
